name: cuteapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  audioplayers: ^6.0.0
  badges: ^3.1.2
  build_runner: ^2.4.6
  cached_network_image: ^3.3.0
  card_swiper: ^3.0.1
  cloud_firestore: ^4.9.2
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  custom_lint: ^0.5.3
  dio: ^5.3.3
  email_validator: ^2.1.17
  firebase_auth: ^4.10.0
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.4
  firebase_storage: ^11.2.8
  flick_video_player: ^0.8.0
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.3.2
  flutter_riverpod: ^2.4.10
  font_awesome_flutter: ^10.5.0
  go_router: ^11.1.2
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  image_picker: ^1.0.4
  intl: ^0.18.0
  msh_checkbox: ^2.0.1
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  random_name_generator: ^1.2.0
  rive: ^0.11.17
  riverpod_annotation: ^2.2.0
  riverpod_generator: ^3.0.0-dev.3
  riverpod_lint: ^2.3.0
  shared_preferences: ^2.2.1
  syncfusion_flutter_pdfviewer: ^24.1.45
  uuid: ^4.1.0
  video_player: ^2.8.7
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
